### ISSUE TITLE
Create "Training Wheels Cap" contract for strategies/vaults to inherit from.

### ISSUE THREAD

**Issue by sirbeefalot** [beefyfinance/beefy-contracts#23]
There are sometimes where we're pushing an experimental vault. Or for a few different reasons, we might want to have a temporary cap on deposits. 

The goal would be to have a reusable contract that lets strategies have a cap for the first x blocks of their existence. 

This would prevent people from apeing $5M into something experimental.

**Comment by yteam-spirit** [comment]
Hi, I think I can do that perfectly.
Could you let me know the details?
Best.
