### ISSUE TITLE
Beefy: Strategy Solarbeam V2 V1 ABI code is different than other ones

### ISSUE THREAD

**Issue by dreamey-eth** [beefyfinance/beefy-contracts#243]
https://moonscan.io/address/0xeccb80e860561ca9ffb183a557f32cc90b05d3c3#readContract
This is the Beefy Strategy contract deployed on Moonbeam network and its abi is a bit different from others.

Means that you are not supporting some of the read methods from the upgraded versions.
Just want to make sure.

**Comment by roman-monk** [comment]
what methods? this strat is deprecated anyway

**Comment by dreamey-eth** [comment]
Just ment the read methds for the fee.
If that is depreciated, that is fine.
